server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

jwt:
  secret:
